// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLA2JHs2eyKDb-JzzHIid1ue9pqBmVyzU',
    appId: '1:720265894839:web:17fe86d0152312be706632',
    messagingSenderId: '720265894839',
    projectId: 'pic-log-222e6',
    authDomain: 'pic-log-222e6.firebaseapp.com',
    storageBucket: 'pic-log-222e6.appspot.com',
    measurementId: 'G-8LHXGFSVK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbvIqWC8qN64PRErLLke9MIe7BnKBkDjw',
    appId: '1:720265894839:android:15911b3f22ae0f79706632',
    messagingSenderId: '720265894839',
    projectId: 'pic-log-222e6',
    storageBucket: 'pic-log-222e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqCIqLjlPbHP63MyIvuiZ8w_KZlSC_Vpo',
    appId: '1:720265894839:ios:e2438d09859e8496706632',
    messagingSenderId: '720265894839',
    projectId: 'pic-log-222e6',
    storageBucket: 'pic-log-222e6.appspot.com',
    iosBundleId: 'com.example.piclogmain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqCIqLjlPbHP63MyIvuiZ8w_KZlSC_Vpo',
    appId: '1:720265894839:ios:e2438d09859e8496706632',
    messagingSenderId: '720265894839',
    projectId: 'pic-log-222e6',
    storageBucket: 'pic-log-222e6.appspot.com',
    iosBundleId: 'com.example.piclogmain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLA2JHs2eyKDb-JzzHIid1ue9pqBmVyzU',
    appId: '1:720265894839:web:b5fd94326d9a9ce6706632',
    messagingSenderId: '720265894839',
    projectId: 'pic-log-222e6',
    authDomain: 'pic-log-222e6.firebaseapp.com',
    storageBucket: 'pic-log-222e6.appspot.com',
    measurementId: 'G-YNHFY2PLGV',
  );
}
